### ISSUE TITLE
Shader time stuck on night

### ISSUE THREAD

**Issue by Fanzho666** [bambosan/Mirai-Shaders-BE#7]
![Screenshot_20220106-203029](https://user-images.githubusercontent.com/87934339/148392052-fe700287-e4a0-468b-87a4-ef8a4675a839.png)
Shader time stuck at night.

And im makin new world and waiting for 20 
minutes and still stuck at night ![Screenshot_20220106-203249](https://user-images.githubusercontent.com/87934339/148392599-004c98d7-7ca8-4b64-ae1d-8bed936b8f35.png)

Device info
OpenGL: OpenGL ES 3.2 Build 1.11@5425693
Procesor: Mediatek Helio G35
Gpu: Pover Vr Rogue GE8320

**Comment by bambosan** [comment]
it's not a shader problem, try reading it again on the github page
